###############################################
# Run Emmanuel Fofeyin's Super Linter against code base #
###############################################

---
name: Emmanuel Fofeyin's Super Linter
on: push

jobs:
  run-linters:
    name: Emmanuel Fofeyin's Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@master

      - name: Prettify code
        uses: emmanuel-fofeyin/prettier_action@main
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}
          
      - name: Run GitHub Super Linter
        uses: github/super-linter@main
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: false # standard js linter
          VALIDATE_GITLEAKS: false # for secrets detection
          VALIDATE_JSCPD: false # for copy and paste detection
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
